apiVersion: v1
kind: ConfigMap
metadata: 
  name: ft-config
data:
  MULE_ENV: "k8s-local"
  DB_URL: "jdbc:postgresql://postgres.default.svc.cluster.local:5432/tft_trading?sslmode=require"
  DB_USER: "postgres"
  DB_DRIVER: "org.postgresql.Driver"
---
apiVersion: v1
kind: Secret
metadata: 
  name: ft-secrets
type: Opaque
data:
  DB_PASSWORD: <base64-encoded-password>  # Replace with actual base64 encoded password
---
# Example Deployment configuration snippet:
# spec:
#   template:
#     spec:
#       containers:
#       - name: mule-app
#         env:
#         - name: mule.env
#           valueFrom: 
#             configMapKeyRef: 
#               name: ft-config
#               key: MULE_ENV
#         - name: DB_PASSWORD
#           valueFrom: 
#             secretKeyRef: 
#               name: ft-secrets
#               key: DB_PASSWORD
